version = 0.1
[default.deploy.parameters]
stack_name = "cognito-react-app-stack"
resolve_s3 = true
s3_prefix = "cognito-react-app-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"dev\" S3BucketName=\"cog-react-app-static-site1241234553\" CognitoUserPoolName=\"cog-react-app-userpool\" CognitoWebClientName=\"cog-react-app-webclient\""
image_repositories = []
